import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ReduxProvider from './lib/redux-provider';
import { Provider } from '@/shared/ui/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Pagination FullStack Test Task',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ReduxProvider>
        <body className={inter.className}>
          <Provider>{children}</Provider>
        </body>
      </ReduxProvider>
    </html>
  );
}
